export const VideoInfo = [
  {
    title: "Most Expensive City in LATIN AMERICA : COSTA RICA 🇨🇷",
    thumb: "yt.png",
    author: "Anushka Sharma",
    view: "500K",
    timeStamp: "2 Days",
    image: "yt.png",
  },
  {
    title: "Epic Drone Footage of the Himalayas 🏔️",
    thumb: "yt.png",
    author: "Adventure Seeker",
    view: Math.floor(Math.random() * 500).toString() + "K",
    timeStamp: Math.floor(Math.random() * 10).toString() + " Days",
    image: "yt.png",
  },
  {
    title: "10 Surprising Facts About Ancient Egypt 🇪🇬",
    thumb: "yt.png",
    author: "History Buff",
    view: Math.floor(Math.random() * 500).toString() + "K",
    timeStamp: Math.floor(Math.random() * 10).toString() + " Days",
    image: "yt.png",
  },
  {
    title: "Building a REST API with Node.js and Express 🚀",
    thumb: "yt.png",
    author: "Coding Guru",
    view: Math.floor(Math.random() * 500).toString() + "K",
    timeStamp: Math.floor(Math.random() * 10).toString() + " Days",
    image: "yt.png",
  },
  {
    title: "Top 10 Most Beautiful Beaches in the World 🏖️",
    thumb: "yt.png",
    author: "Travel Enthusiast",
    view: Math.floor(Math.random() * 500).toString() + "K",
    timeStamp: Math.floor(Math.random() * 10).toString() + " Days",
    image: "yt.png",
  },
  {
    title: "The Rise of Artificial Intelligence: A Documentary",
    thumb: "yt.png",
    author: "Tech Visionary",
    view: Math.floor(Math.random() * 500).toString() + "K",
    timeStamp: Math.floor(Math.random() * 10).toString() + " Days",
    image: "yt.png",
  },
];
